sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vanessa-c-ramos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vanessa-c-ramos/docker-react npm run test -- --coverage
